const INGREDIENTS = Object.freeze({
    SALAD: 'salad',
    CHEESE: 'cheese',
    MEAT: 'meat',
    BACON: 'bacon'
});

const INGREDIENT_QUANTITIES = Object.freeze({
    [INGREDIENTS.SALAD]: 1,
    [INGREDIENTS.CHEESE]: 1,
    [INGREDIENTS.MEAT]: 1,
    [INGREDIENTS.BACON]: 1
})
 
const INGREDIENT_NAMES = Object.freeze({
    [INGREDIENTS.SALAD]: 'Salad',
    [INGREDIENTS.CHEESE]: 'Cheese',
    [INGREDIENTS.MEAT]: 'Meat',
    [INGREDIENTS.BACON]: 'Bacon'
});
 
const INGREDIENT_PRICES = Object.freeze({
    [INGREDIENTS.SALAD]: 1,
    [INGREDIENTS.CHEESE]: 1,
    [INGREDIENTS.MEAT]: 2,
    [INGREDIENTS.BACON]: 1.50
});
 
const BASE_BURGER_PRICE = 4;
 
export { INGREDIENTS, INGREDIENT_QUANTITIES, INGREDIENT_NAMES, INGREDIENT_PRICES, BASE_BURGER_PRICE };